version: '3'
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'docker'
      POSTGRES_USER: 'docker'

  seed:
    image: amazoncorretto:11
    expose:
      - '8080'
      - '1600'
      - '9100'
    environment:
      DB_HOST: postgres
      CLUSTER_PORT: 1600
      CLUSTER_IP: seed
      SEED_PORT_1600_TCP_ADDR: seed
    entrypoint: java -Dconfig.file=/app/compose.conf -jar /app/app.jar
    volumes:
      - '../booking-service/build/libs/booking-service.jar:/app/app.jar:ro'
      - './compose.conf:/app/compose.conf:ro'
    depends_on:
      - postgres

  akka1:
    image: amazoncorretto:11
    expose:
      - '8080'
      - '1600'
      - '9100'
    environment:
      DB_HOST: postgres
      CLUSTER_PORT: 1600
      CLUSTER_IP: akka1
      SEED_PORT_1600_TCP_ADDR: seed
    entrypoint: java -Dconfig.file=/app/compose.conf -jar /app/app.jar
    volumes:
      - '../booking-service/build/libs/booking-service.jar:/app/app.jar:ro'
      - './compose.conf:/app/compose.conf:ro'
    depends_on:
      - seed

  akka2:
    image: amazoncorretto:11
    expose:
      - '8080'
      - '1600'
      - '9100'
    environment:
      DB_HOST: postgres
      CLUSTER_PORT: 1600
      CLUSTER_IP: akka2
      SEED_PORT_1600_TCP_ADDR: seed
    entrypoint: java -Dconfig.file=/app/compose.conf -jar /app/app.jar
    volumes:
      - '../booking-service/build/libs/booking-service.jar:/app/app.jar:ro'
      - './compose.conf:/app/compose.conf:ro'
    depends_on:
      - seed

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - akka1
      - akka2
    ports:
      - "9000:9000"
