POST http://localhost:8081
Content-Type: application/json

{"name": "Destination", "capacity": 10}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});

client.global.set("trip_location", response.headers.valueOf("Location"));
%}

###

GET http://localhost:8081{{trip_location}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
client.test("Trip total capacity is equal to defined capacity", function() {
  client.assert(response.body.totalCapacity === 10, "Full capacity should be available");
});
client.test("Trip remaining capacity is equal to full capacity", function() {
  client.assert(response.body.remainingCapacity === response.body.totalCapacity, "Full capacity should be available");
});
%}

###

POST http://localhost:8081{{trip_location}}/reservations
Content-Type: application/json

{"name": "John", "capacity": 2}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
client.global.set("john_reservation_location", response.headers.valueOf("Location"));
%}

###

GET http://localhost:8081{{trip_location}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
client.test("Trip remaining capacity is reduced", function() {
  client.assert(response.body.remainingCapacity === 8, "Remaining capacity is not 8");
});
%}

###

PATCH http://localhost:8081{{john_reservation_location}}/capacity
Content-Type: application/json

3

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

PATCH http://localhost:8081{{john_reservation_location}}/name
Content-Type: application/json

"Jane"

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

POST http://localhost:8081{{trip_location}}/reservations
Content-Type: application/json

{"name": "Ronald", "capacity": 7}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}

###

GET http://localhost:8081{{trip_location}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
client.test("Trip remaining capacity is reduced", function() {
  client.assert(response.body.remainingCapacity === 0, "Remaining capacity is not 0");
});
%}

###

DELETE http://localhost:8081{{john_reservation_location}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 204, "Response status is not 204");
});
%}

###

GET http://localhost:8081{{trip_location}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
client.test("Trip remaining capacity is equal to full capacity minus reservation of Ronald", function() {
  client.assert(response.body.remainingCapacity === response.body.totalCapacity - 7, "Unexpected remaining capacity");
});
%}

###
